### ISSUE TITLE
Be careful with using real names in references

### ISSUE THREAD

**Issue by zloysmiertniy** [inzva/fake-academic-paper-generation#1]
Good day.

I found that one of your "fake" papers is actually a paper from the research group I belong to. I asume that you are simply scraping arxiv. Please do something different and generate new human names, this is not very hard to do. Both title and authors are real. So please check this. 

The paper is [here](https://github.com/inzva/fake-academic-paper-generation/blob/95d96bf93f620fffcc6a023423846af7bd71d44d/dataset/290.tex) 

Maybe this is used for training or something. But we would really appreciate it if you didn't use this paper for training fake academic paper generation or at least remove the authors names.

Thank you

**Comment by urasmutlu** [comment]
Hi there,

Thank you for expressing your concern. We scraped arXiv but the papers in arXiv have creative commons license. So as long as the papers we have used are properly cited and licensed accordingly, we don't think it would be a problem to use open access paper sources as training data. We used your paper and lots of others to only train our model, so your paper was not a generated (or "fake") one.

A fake paper generated by our model is very unlikely to directly imitate real author names and especially a whole research group. If a fake paper generated by our model contains actual authors and research groups it would be totally coincidental and I don't believe that the actual authors would be responsible from any kind of misuse. 

We understand your concerns and removed your paper from the repository.

Cheers,
Uras
