### ISSUE TITLE
how to create "preprocessed_data.txt"

### ISSUE THREAD

**Issue by javafish** [inzva/fake-academic-paper-generation#2]
Hi, I try to run the char-rnn.py but notice that there is no file called "preprocessed_data.txt". Can you pls kindly let me know how to create it?

Cheers

**Comment by simitii** [comment]
Hi, please see [the Dataset section of README](https://github.com/inzva/fake-academic-paper-generation#dataset).

**Comment by javafish** [comment]
hi, we did follow the process but it seems only created 1000 .tex file in the dataset directory, and we cannot find the "preprocessed_data.txt"....

**Comment by simitii** [comment]
> hi, we did follow the process but it seems only created 1000 .tex file in the dataset directory, and we cannot find the "preprocessed_data.txt"....

Great. I assume you have run the preprocess_char.py script, which outputs preprocessed .tex files. Next, we concatenate (merge) the 1000 .tex files to create "preprocessed_data.txt", a text file that includes the complete dataset. To do so, we use the following unix/linux command: 
```cat dataset/*.tex > preprocessed_data.txt```

It is important to note that this (our) approach does not treat each paper (.tex file) separately, instead it treats the complete dataset (preprocessed_data.txt) as one single text.

**Comment by javafish** [comment]
Thanks, it works now. Have a good day.

**Comment by urasmutlu** [comment]
Thank you, closing the issue.
